import type { Product, ShopifyImage } from "@/lib/shopify/types";
import data from "./catalog.json";
import radar from "./radar-products.json";
import retired from "./retired.json";
import extra from "./extra-images.json";

// catalog.json is generated by `npm run catalog` — never edit it by hand.
// radar-products.json: pairs published from Beyond Radar (kept separate so a
// catalogue rebuild never erases them). extra-images.json: BEYOND PLUS's own
// photos added from Radar (handle → images).
const EXTRA = extra as Record<string, ShopifyImage[]>;
const BASE = data as Product[];
const handles = new Set(BASE.map((p) => p.handle));
// Radar titles and alt texts can carry " - " or " — " (house style forbids them in
// visible text): rewrite them as a comma. Handles and URLs never contain spaces.
const RADAR = JSON.parse(JSON.stringify(radar).replace(/ [-–—] /g, ", ")) as Product[];
// A pair retired by the curator (retired.json) is never shown, even when Radar
// published it too: its URL redirects like any retired product.
const gone = new Set((retired as { handle: string }[]).map((r) => r.handle));
export const CATALOG = [...BASE, ...RADAR.filter((p) => !handles.has(p.handle))].filter((p) => !gone.has(p.handle)).map((p) =>
  EXTRA[p.handle]?.length ? { ...p, images: [...p.images, ...EXTRA[p.handle].filter((e) => !p.images.some((i) => i.url === e.url))] } : p,
);
export const PRODUCT_BY_HANDLE = new Map(CATALOG.map((p) => [p.handle, p]));
