/* ============================================================================
   Shopify Storefront API, domain types
   ----------------------------------------------------------------------------
   These mirror the shapes returned by the Storefront GraphQL API so that the
   mock adapter in `./mock.ts` can be swapped for `./client.ts` (a real
   Storefront fetch) without touching a single component.
   ========================================================================= */

export interface Money {
  amount: string;          // "119.00"
  currencyCode: string;    // "MAD"
}

export interface ShopifyImage {
  url: string;
  altText: string | null;
  width: number;
  height: number;
}

export interface SelectedOption {
  name: string;            // "Size" | "Color"
  value: string;           // "M" | "Black"
}

export interface ProductVariant {
  id: string;              // gid://shopify/ProductVariant/…
  title: string;
  availableForSale: boolean;
  quantityAvailable: number | null;
  selectedOptions: SelectedOption[];
  price: Money;
  compareAtPrice: Money | null;
  image: ShopifyImage | null;
  sku: string | null;
}

export interface ProductOption {
  id: string;
  name: string;
  values: string[];
}

/** Metafields we read on the PDP — mirrors `product.metafields(identifiers:)` */
export interface ProductMetafields {
  fit?: string;            // "Regular Fit"
  modelNote?: string;      // "Model is 1m78 and wears a M"
  composition?: string;    // rich text (HTML)
  care?: string;           // rich text (HTML)
  details?: string;        // rich text (HTML)
  shipping?: string;       // rich text (HTML)
  /** Internal sourcing reference — never shown on the storefront.
   *  Maps to a real Shopify metafield (`custom.original_url` /
   *  `custom.original_price_label`) once these products are recreated in
   *  Shopify; kept here only so buying/pricing decisions stay traceable. */
  originalUrl?: string;
  originalPriceLabel?: string;  // e.g. "185,00 €" — the source-site listed price
}

/** BEYOND PLUS merchandising data, generated by catalog/build.ts. */
export interface ProductMerch {
  brand: string;
  model: string;
  silhouette: string;
  colorway: string;
  color: string;
  gender: "women" | "men" | "unisex";
  style: string;
  collections: string[];
  label: "NEW IN" | "TRENDING" | "BEYOND PICK" | null;
  rank: number;          // internal score, never displayed
  homeRank: number | null;
}

export interface Product {
  previewOnly?: boolean;
  merch?: ProductMerch;
  id: string;
  handle: string;
  title: string;
  description: string;
  descriptionHtml: string;
  vendor: string;
  productType: string;
  tags: string[];
  availableForSale: boolean;
  featuredImage: ShopifyImage | null;
  images: ShopifyImage[];
  options: ProductOption[];
  variants: ProductVariant[];
  priceRange: { minVariantPrice: Money; maxVariantPrice: Money };
  compareAtPriceRange: { minVariantPrice: Money; maxVariantPrice: Money } | null;
  metafields: ProductMetafields;
}

export interface Collection {
  id: string;
  handle: string;
  title: string;
  description: string;
  image: ShopifyImage | null;
  products: Product[];
}

/* ---- Cart (Storefront Cart API shape) ----------------------------------- */

export interface CartLine {
  id: string;
  quantity: number;
  merchandise: {
    id: string;               // variant id
    title: string;            // variant title, e.g. "M"
    selectedOptions: SelectedOption[];
    image: ShopifyImage | null;
    price: Money;
    product: { handle: string; title: string };
  };
  cost: { totalAmount: Money };
}

export interface Cart {
  id: string | null;
  checkoutUrl: string | null;
  totalQuantity: number;
  lines: CartLine[];
  cost: {
    subtotalAmount: Money;
    totalAmount: Money;
  };
}

/* ---- Customer (Shopify `customer` object, minimal) ----------------------- */

export interface Customer {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  createdAt: string; // ISO date
}

/* ---- Navigation (Shopify `menu` / linklists) ---------------------------- */

export interface MenuImageCard {
  title: string;
  href: string;
  image: string;
}

export interface MenuColumn {
  title: string;
  items: { title: string; href: string }[];
}

export interface MenuItem {
  title: string;
  href: string;
  type: "link" | "dropdown" | "mega";
  columns?: MenuColumn[];
  cards?: MenuImageCard[];
}
